<a href="https://colab.research.google.com/github/rishellevarghees/MLDA/blob/main/DATA_PREPROCESSING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

data = pd.read_csv('House Price India.csv', encoding="latin1")
print(data.head())


data = data.rename(columns={
    'living area': 'Size (sqft)',
    'number of bedrooms': 'Rooms',
    'Built Year': 'Age (years)',
    'Price': 'Price (INR)',
    'Postal Code': 'Location'
})

for col in ['Size (sqft)', 'Age (years)', 'Price (INR)']:
    data[col] = data[col].replace(',', '', regex=True).astype(float)

num_features = ['Size (sqft)', 'Rooms', 'Age (years)', 'Price (INR)']
num_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

cat_features = ['Location']
cat_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_transformer, ['Size (sqft)', 'Rooms', 'Age (years)']),
        ("cat", cat_transformer, cat_features)
    ]
)
preprocessor.set_output(transform="pandas")

data_preprocessed = preprocessor.fit_transform(data)
print(data_preprocessed.head())

preprocessor_Out = ColumnTransformer(
    transformers=[
        ("num", num_transformer, ['Price (INR)'])
    ]
)
preprocessor_Out.set_output(transform="pandas")

data_preprocessed_Out = preprocessor_Out.fit_transform(data)
print(data_preprocessed_Out.head())

data_preprocessed["Price_per_sqft"] = data['Price (INR)'] / data['Size (sqft)']

X = data_preprocessed
y = data_preprocessed_Out
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.head())
print(y_train.head())

           id   Date  number of bedrooms  number of bathrooms  living area  \
0  6762810635  42491                   4                 2.50         2920
1  6762810998  42491                   5                 2.75         2910
2  6762812605  42491                   4                 2.50         3310
3  6762812919  42491                   3                 2.00         2710
4  6762813105  42491                   3                 2.50         2600

   lot area  number of floors  waterfront present  number of views  \
0      4000               1.5                   0                0
1      9480               1.5                   0                0
2     42998               2.0                   0                0
3      4500               1.5                   0                0
4      4750               1.0                   0                0

   condition of the house  ...  Built Year  Renovation Year  Postal Code  \
0                       5  ...        1909                0       122004
1                       3  ...        1939                0       122004
2                       3  ...        2001                0       122005
3                       4  ...        1929                0       122006
4                       4  ...        1951                0       122007

   Lattitude  Longitude  living_area_renov  lot_area_renov  \
0    52.8878   -114.470               2470            4000
1    52.8852   -114.468               2940            6600
2    52.9532   -114.321               3350           42847
3    52.9047   -114.485               2060            4500
4    52.9133   -114.590               2380            4750

   Number of schools nearby  Distance from the airport    Price
0                         2                         51  1400000
1                         1                         53  1200000
2                         3                         76   838000
3                         1                         51   805000
4                         1                         67   790000

[5 rows x 23 columns]
   num__Size (sqft)  num__Rooms  num__Age (years)  cat__Location_122003  \
0          0.885428    0.661360         -2.099975                   0.0
1          0.874655    1.726750         -1.082707                   0.0
2          1.305602    0.661360          1.019648                   0.0
3          0.659181   -0.404031         -1.421796                   0.0
4          0.540670   -0.404031         -0.675799                   0.0

   cat__Location_122004  cat__Location_122005  cat__Location_122006  \
0                   1.0                   0.0                   0.0
1                   1.0                   0.0                   0.0
2                   0.0                   1.0                   0.0
3                   0.0                   0.0                   1.0
4                   0.0                   0.0                   0.0

   cat__Location_122007  cat__Location_122008  cat__Location_122009  ...  \
0                   0.0                   0.0                   0.0  ...
1                   0.0                   0.0                   0.0  ...
2                   0.0                   0.0                   0.0  ...
3                   0.0                   0.0                   0.0  ...
4                   1.0                   0.0                   0.0  ...

   cat__Location_122063  cat__Location_122064  cat__Location_122065  \
0                   0.0                   0.0                   0.0
1                   0.0                   0.0                   0.0
2                   0.0                   0.0                   0.0
3                   0.0                   0.0                   0.0
4                   0.0                   0.0                   0.0

   cat__Location_122066  cat__Location_122067  cat__Location_122068  \
0                   0.0                   0.0                   0.0
1                   0.0                   0.0                   0.0
2                   0.0                   0.0                   0.0
3                   0.0                   0.0                   0.0
4                   0.0                   0.0                   0.0

   cat__Location_122069  cat__Location_122070  cat__Location_122071  \
0                   0.0                   0.0                   0.0
1                   0.0                   0.0                   0.0
2                   0.0                   0.0                   0.0
3                   0.0                   0.0                   0.0
4                   0.0                   0.0                   0.0

   cat__Location_122072
0                   0.0
1                   0.0
2                   0.0
3                   0.0
4                   0.0

[5 rows x 73 columns]
   num__Price (INR)
0          2.345192
1          1.800554
2          0.814760
3          0.724895
4          0.684047
       num__Size (sqft)  num__Rooms  num__Age (years)  cat__Location_122003  \
2996          -0.461283   -0.404031          0.239743                   0.0
1369          -0.515151   -0.404031          0.578832                   0.0
740           -0.342772   -0.404031          0.511014                   0.0
9527          -0.267357   -0.404031          0.578832                   0.0
10324         -0.730625   -0.404031         -0.302801                   0.0

       cat__Location_122004  cat__Location_122005  cat__Location_122006  \
2996                    0.0                   0.0                   0.0
1369                    0.0                   0.0                   0.0
740                     0.0                   0.0                   0.0
9527                    0.0                   0.0                   0.0
10324                   0.0                   0.0                   0.0

       cat__Location_122007  cat__Location_122008  cat__Location_122009  ...  \
2996                    0.0                   0.0                   0.0  ...
1369                    0.0                   0.0                   0.0  ...
740                     0.0                   0.0                   0.0  ...
9527                    0.0                   0.0                   0.0  ...
10324                   0.0                   0.0                   0.0  ...

       cat__Location_122064  cat__Location_122065  cat__Location_122066  \
2996                    0.0                   0.0                   0.0
1369                    0.0                   0.0                   0.0
740                     0.0                   1.0                   0.0
9527                    0.0                   0.0                   0.0
10324                   0.0                   0.0                   0.0

       cat__Location_122067  cat__Location_122068  cat__Location_122069  \
2996                    0.0                   0.0                   0.0
1369                    0.0                   0.0                   0.0
740                     0.0                   0.0                   0.0
9527                    0.0                   0.0                   0.0
10324                   0.0                   0.0                   0.0

       cat__Location_122070  cat__Location_122071  cat__Location_122072  \
2996                    0.0                   0.0                   0.0
1369                    0.0                   0.0                   0.0
740                     0.0                   0.0                   0.0
9527                    0.0                   0.0                   0.0
10324                   0.0                   0.0                   0.0

       Price_per_sqft
2996       143.682635
1369       159.259259
740        149.438202
9527       156.216216
10324      157.814789

[5 rows x 74 columns]
       num__Price (INR)
2996          -0.813842
1369          -0.764688
740           -0.742903
9527          -0.680269
10324         -0.857012